services:
  api:
    image: opentourney-api
    build: opentourney-api
    network_mode: "host"
    env_file:
      - opentourney-api/env/dev.env
    ports:
      - "3000:3000"
  frontend:
    image: opentourney-frontend
    build: opentourney
    ports:
      - "80:80"
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
    driver: local